on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    name: A job to triage issues
    steps:
      - name: check the text
        id: triage
        uses: rstudio/issuetriager@main
        with:
          check-phrase: 'this is a blocking issue'
          issue-body: ${{ github.
      # Use the output from the `triage` step
      - name: Label the issue as blocking
        if: ${{ steps.triage.outputs.contains-phrase }}
        uses: andymckay/labeler@master
        with:
          add-labels: "blocking"
